name: torrid
description: "A Useful and Great App."


version: 1.0.0+1

environment:
  sdk: ^3.8.1

# 应用依赖
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # ----运行依赖----
  # 状态管理riverpod
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.3.0
  # 数据持久化方案. Hive, shared_preferences
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  # 路径获取及处理.
  path_provider: ^2.1.5
  path: ^1.9.1
  # 路由管理
  go_router: ^16.1.0
  # 权限管理
  permission_handler: ^12.0.1
  # id生成
  uuid: ^4.5.2


  # ----网络----
  # http请求
  http: ^1.5.0
  # 更强大的网络请求.
  dio: ^5.9.0


  # ----更好的显示----
  # 时间格式化
  intl: ^0.20.2
  # 拼音排序支持
  pinyin: ^3.3.0
  # markdown渲染
  flutter_markdown_plus: ^1.0.5
  # TODO: 代码高亮.
  # flutter_highlight: ^0.7.0
  # 日志logging
  logging: ^1.3.0


  # ----媒体文件相关----
  # 视频播放
  # chewie: ^1.12.1
  # video_player: ^2.10.0
  # 本地图片选择
  image_picker: ^1.2.0
  # # 图片压缩
  # flutter_image_compress: ^2.4.0
  # 查看图片
  photo_view: ^0.15.0
  # 图片处理库
  image_size_getter: ^2.4.1
  # # 图片的网络、缓存
  # cached_network_image: ^3.4.1
  # 图像处理库
  image: ^4.5.4


  # ----成熟库----
  flutter_slidable: ^4.0.3


  # ----codegen代码生成----
  json_annotation: ^4.9.0
  

# 开发时插件-------:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # 代码生成.
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  riverpod_generator: ^2.3.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/files/
    # - assets/videos/
    - assets/icons/
  fonts:
    # 楷体  自然美感, 适合小段落,副标题.
    - family: kaiti
      fonts:
        - asset: assets/fonts/kaiti.ttf
    # 新宋  清晰规整, 适合正文
    - family: xinsong
      fonts:
        - asset: assets/fonts/xinsong.ttc
    # 仿宋  庄重典雅, 适合典籍引用.
    - family: fangsong
      fonts:
        - asset: assets/fonts/fangsong.ttf
    # iconfont
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf

